// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for ebcalcnoticia documents
 */
interface EbcalcnoticiaDocumentData {
  /**
   * titulonoticia field in *ebcalcnoticia*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ebcalcnoticia.titulonoticia
   * - **Tab**: NoticiaPage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulonoticia: prismic.KeyTextField;

  /**
   * subtitulo field in *ebcalcnoticia*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ebcalcnoticia.subtitulo
   * - **Tab**: NoticiaPage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * datanoticia field in *ebcalcnoticia*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: ebcalcnoticia.datanoticia
   * - **Tab**: NoticiaPage
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  datanoticia: prismic.DateField;

  /**
   * image field in *ebcalcnoticia*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ebcalcnoticia.image
   * - **Tab**: NoticiaPage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * textonoticia field in *ebcalcnoticia*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ebcalcnoticia.textonoticia
   * - **Tab**: NoticiaPage
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textonoticia: prismic.RichTextField;
}

/**
 * ebcalcnoticia document from Prismic
 *
 * - **API ID**: `ebcalcnoticia`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EbcalcnoticiaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EbcalcnoticiaDocumentData>,
    "ebcalcnoticia",
    Lang
  >;

export type AllDocumentTypes = EbcalcnoticiaDocument;

/**
 * Default variation for Ebcalc Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EbcalcSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Ebcalc*
 */
type EbcalcSliceVariation = EbcalcSliceDefault;

/**
 * Ebcalc Shared Slice
 *
 * - **API ID**: `ebcalc`
 * - **Description**: Ebcalc
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EbcalcSlice = prismic.SharedSlice<"ebcalc", EbcalcSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EbcalcnoticiaDocument,
      EbcalcnoticiaDocumentData,
      AllDocumentTypes,
      EbcalcSlice,
      EbcalcSliceVariation,
      EbcalcSliceDefault,
    };
  }
}
